services:
  frontend:
    build:
      context: ./front
      target: development
      args:
        NODE_ENV: development
    ports:
      - "${CLIENT_PORT:-5173}:5173"
    volumes:
      - ./front:/usr/app
      - /usr/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    # networks:
    #   - colocaton-network

  backend:
    build:
      context: ./back
      target: development
      args:
        NODE_ENV: development
    ports:
      - "${BACK_PORT:-5000}:5000"
    volumes:
      - ./back:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${BACK_PORT:-5000}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    # networks:
    #   - colocaton-network
